// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkbaexlcbBz9sGPNldp0o-aLrc5YXjVI',
    appId: '1:115930194142:web:b027c2fe793e7c0f84624f',
    messagingSenderId: '115930194142',
    projectId: 'typit-dd0bf',
    authDomain: 'typit-dd0bf.firebaseapp.com',
    storageBucket: 'typit-dd0bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYnxbvtc-hzpcuMxV5-6jQnJVWiL4GuI',
    appId: '1:115930194142:android:45d7d3b5169027ac84624f',
    messagingSenderId: '115930194142',
    projectId: 'typit-dd0bf',
    storageBucket: 'typit-dd0bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpL3ZFUow4oa5sZPcCioLI0mca7BTmq4',
    appId: '1:115930194142:ios:2094f9382b7b5b8e84624f',
    messagingSenderId: '115930194142',
    projectId: 'typit-dd0bf',
    storageBucket: 'typit-dd0bf.appspot.com',
    iosClientId: '115930194142-3ocsdbvukndl8go71bagguih0muakhaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpL3ZFUow4oa5sZPcCioLI0mca7BTmq4',
    appId: '1:115930194142:ios:2094f9382b7b5b8e84624f',
    messagingSenderId: '115930194142',
    projectId: 'typit-dd0bf',
    storageBucket: 'typit-dd0bf.appspot.com',
    iosClientId: '115930194142-3ocsdbvukndl8go71bagguih0muakhaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
